# Generated by Django 4.1 on 2022-11-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_announcement_date_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp863', max_length=70),
        ),
    ]
