# Generated by Django 4.1 on 2022-10-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kin',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Recruitment',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Kin',
        ),
    ]
